# Generated by Django 5.1.3 on 2024-11-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="category",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
