# List of allowed mimetypes with their extensions
MIMETYPE_EXTENSIONS_MAP = {
    "text/plain": ["txt"],
    "text/html": ["html", "htm"],
    "text/css": ["css"],
    "text/javascript": ["js"],
    "text/xml": ["xml"],
    "application/json": ["json"],
    "application/xml": ["xml"],
    "text/csv": ["csv"],
    "image/jpeg": ["jpg", "jpeg"],
    "image/png": ["png"],
    "image/gif": ["gif"],
    "image/bmp": ["bmp"],
    "image/webp": ["webp"],
    "image/svg+xml": ["svg"],
    "image/tiff": ["tiff"],
    "image/x-icon": ["ico"],
    "audio/mpeg": ["mp3"],
    "audio/wav": ["wav"],
    "audio/ogg": ["ogg"],
    "audio/aac": ["aac"],
    "audio/flac": ["flac"],
    "audio/webm": ["webm"],
    "video/mp4": ["mp4"],
    "video/webm": ["webm"],
    "video/ogg": ["ogg"],
    "video/avi": ["avi"],
    "video/mpeg": ["mpeg"],
    "video/quicktime": ["mov"],
    "video/x-msvideo": ["avi"],
    "application/pdf": ["pdf"],
    "application/msword": ["doc"],
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": ["docx"],
    "application/vnd.ms-excel": ["xls"],
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": ["xlsx"],
    "application/vnd.ms-powerpoint": ["ppt"],
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": [
        "pptx"
    ],
    "application/rtf": ["rtf"],
    "application/epub+zip": ["epub"],
    "application/zip": ["zip"],
    "application/x-tar": ["tar"],
    "application/gzip": ["gz", "gzip"],
    "application/x-7z-compressed": ["7z"],
    "application/x-rar-compressed": ["rar"],
    "application/x-shockwave-flash": ["swf"],
    "application/x-java-archive": ["jar"],
    "font/woff": ["woff"],
    "font/woff2": ["woff2"],
    "application/font-woff": ["woff"],
    "application/font-woff2": ["woff2"],
    "font/otf": ["otf"],
    "font/ttf": ["ttf"],
    "application/x-www-form-urlencoded": ["urlencoded"],
    "application/wasm": ["wasm"],
}


MAX_FILE_SIZE = 10 * 1024 * 1024
